TableTennisChampionship/TableTennisChampionshipMain/Areas/Administration/Controllers/PlayerInformationController.cs
namespace TableTennisChampionshipMain.Areas.Administration.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Mvc;
    using TableTennisChampionshipData;
    using WorkingWithDataMvc.Data;
    using TableTennisChampionshipMain.ViewModels;
    using TableTennisChampionship.Model.DataBaseModel;
    using AutoMapper.QueryableExtensions;
    using Microsoft.WindowsAzure.Storage;
    using Microsoft.WindowsAzure.Storage.Auth;
    using Microsoft.WindowsAzure.Storage.Blob;
    using Microsoft.WindowsAzure;

    [Authorize(Roles = "Admin")]
    public class PlayerInformationController : Controller
    {
        private readonly IRepository<Player> player;
        //Конструктор,който приема репозитори, подадено му от ninject
        public PlayerInformationController(IRepository<Player> player) {
            this.player = player;
           

        }
        // GET: /Administration/PlayerInfo/
        public ActionResult Index()
        {
            var playerList = player.All()
                .Project()
                .To<PlayerInfo>();
            return View(playerList);
        }

        // GET: /Administration/PlayerInfo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var SelectedPlayer = this.player.All()
                .Where(p => p.PlayerID == id)
                .Project()
                .To<TableTennisChampionshipMain.ViewModels.PlayerInfo>()
                .FirstOrDefault();

            if (SelectedPlayer == null)
            {
                return HttpNotFound();
            }
            return View(SelectedPlayer);
        }

        // GET: /Administration/PlayerInfo/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: /Administration/PlayerInfo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlayerID,FirstName,LastName,PhotoFile,Age,PostedFile")] TableTennisChampionshipMain.ViewModels.PlayerInfo player)
        {
            if (ModelState.IsValid)
            {        
                if (player.PostedFile.ContentLength > 0) 
                {
                    //Запазвам профилната снимкав папка Pictures
                    var fileName = System.IO.Path.GetFileName(player.PostedFile.FileName);
                    #region CommetFileSaveOnContentFolder
                    //var path = System.IO.Path.Combine(Server.MapPath("~/Content/Pictures/"), fileName);
                    //var path = System.IO.Path.Combine(Server.MapPath("~/"), fileName);
                    //player.PostedFile.SaveAs(path);
                    #endregion
                    //Запазвам файлът в AzureStorage
                    AzureStorageHelper azureHelper = new AzureStorageHelper();
                    azureHelper.CreateBlob(fileName, player.PostedFile);
                    Player entityPlayer = new Player
                    {
                        FirstName = player.FirstName,
                        LastName = player.LastName,
                        PhotoFile = fileName,
                        Age = player.Age,
                        ImageUrl=azureHelper.FullBlobUrl(fileName)
                    };
                    //Добавям новото entity и записвам
                    this.player.Add(entityPlayer);
                    this.player.SaveChanges();
                }
                //Връщам към списъка
                return RedirectToAction("Index");
            }
            //При грешка връщам обработения модел
            return View(player);
        }

        // GET: /Administration/PlayerInfo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var SelectedPlayer = this.player.All()
                .Where(p => p.PlayerID == id)
                .Project()
                .To<TableTennisChampionshipMain.ViewModels.PlayerInfo>()
                .FirstOrDefault();

            if (SelectedPlayer == null)
            {
                return HttpNotFound();
            }
            //else
            //{
             
            //}
            return View(SelectedPlayer);
        }

        // POST: /Administration/PlayerInfo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlayerID,FirstName,LastName,PhotoFile,Age,PlayerID,ImageUrl,PostedFile")] TableTennisChampionshipMain.ViewModels.PlayerInfo player)
        {

            if (ModelState.IsValid)
            {
                if (player.PostedFile != null && player.PostedFile.ContentLength > 0)
                {
                    var fileName = System.IO.Path.GetFileName(player.PostedFile.FileName);
                    AzureStorageHelper azureHelper = new AzureStorageHelper();
                    //създава се нов блоб възоснова на поснатия файл
                    azureHelper.CreateBlob(fileName, player.PostedFile);
                    // изтрива се предишния, неговото име се държи във viewmodel
                    azureHelper.DeleteBlob(player.PhotoFile);
                    // сетват се нови стойности на полета от viewmodel
                    player.ImageUrl = azureHelper.FullBlobUrl(fileName);
                    player.PhotoFile = fileName;

                }

                Player entityPlayer = new Player
                {
                    PlayerID=player.PlayerID,
                    FirstName = player.FirstName,
                    LastName = player.LastName,
                    PhotoFile =player.PhotoFile,
                    Age = player.Age,
                    ImageUrl=player.ImageUrl
                };
                this.player.Update(entityPlayer);
                this.player.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(player);
        }

        // GET: /Administration/PlayerInfo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Player player = db.Players.Find(id);
            //if (player == null)
            //{
            //    return HttpNotFound();
            //}
            return View(player);
        }

        // POST: /Administration/PlayerInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //Player player = db.Players.Find(id);
            //db.Players.Remove(player);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TableTennisChampionship/TableTennisChampionshipMain/Areas/Administration/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TableTennisChampionship.Model.DataBaseModel;
using WorkingWithDataMvc.Data;
using System.Data.Entity;
using AutoMapper.QueryableExtensions;
using System.Net;
using TableTennisChampionshipMain.ViewModels;

namespace TableTennisChampionshipMain.Areas.Administration.Controllers
{
    public class TournamentController : Controller
    {
        private readonly IRepository<Tournament> tournament;
        private readonly IRepository<AdvanceGroupCriteria> _AdvanceGroupCriteria;
        private readonly IRepository<TournamentType> _TournamenType;
        private readonly IRepository<Player> player;

        //Конструктор,който приема репозитори, подадено му от ninject
        public TournamentController(IRepository<Tournament> tournament, IRepository<AdvanceGroupCriteria> advanceGroupCriteria, IRepository<TournamentType> tournamenType, IRepository<Player> player)
        {
            this.tournament = tournament;
            this._AdvanceGroupCriteria = advanceGroupCriteria;
            this._TournamenType = tournamenType;
            this.player=player;
        }
        // GET: Administration/Tournament
        public ActionResult Index()
        {
            var tournamentList = this.tournament.All()
                .Include(x => x.TournamentType)
                .Include(x => x.AdvanceGroupCriteria)
                .Include("TournamentPlayers")
                .Project()
                .To<TableTennisChampionshipMain.ViewModels.TournamentInfo>();

            //selectedTournament.First().FirstPlacePlayer.
            return View(tournamentList);
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.AdvanceCriteria = AdvanceCriteriaDDL();
            ViewBag.TournamentType = TournamentTypeDDL();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TableTennisChampionshipMain.ViewModels.TournamentInfo trmt)
        {
            Tournament _entityTour =null;
            try
            {
                if (ModelState.IsValid)
                {
                    _entityTour = new Tournament
                    {
                        TournamentName=trmt.TournamentName,
                        AdvanceGroupCriteriaID=trmt.AdvanceGroupCriteriaID,
                        TournamentTypeID=trmt.TournamentTypeID,
                        StartDate=(DateTime)trmt.StartDate,
                        EndDate=(DateTime)trmt.EndDate
                    };
                    this.tournament.Add(_entityTour);
                    this.tournament.SaveChanges();
                    return RedirectToAction("Index");
                }
                
            }
            catch(Exception ex) 
            { 
            
            }
            return View(trmt);  
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var selectTour = this.tournament.All()
                .Where(x => x.TournamentID == id)
                .Project()
                .To<TableTennisChampionshipMain.ViewModels.TournamentInfo>()
                .FirstOrDefault();
            ViewBag.AdvanceCriteria = AdvanceCriteriaDDL();
            ViewBag.TournamentType = TournamentTypeDDL();
            ViewBag.Ranks = RanksDDL();
            if (selectTour == null)
            {
                return HttpNotFound();
            }
            return View(selectTour);
        }
        #region "Private Methods"
        /// <summary>
        /// Връща ViewBag за комбо бокс-продължаване в групата  
        /// </summary>
        /// <returns></returns>
        private SelectList AdvanceCriteriaDDL()
        {
            List<SelectListItem> result = new List<SelectListItem>();
            var listAC = (from lst in _AdvanceGroupCriteria.All()
                         select new 
                         { 
                         ID=lst.AdvanceGroupCriteriaID,
                         Name=lst.AdvanceGroupCriteriaDescription
                         }
                         ).ToList();
            result.AddRange(new SelectList( listAC, "ID", "Name"));
            return new SelectList(result, "Value", "Text");
        }
        /// <summary>
        /// Връща ЖиевБаг за комбо бокс- тип на турнира
        /// </summary>
        /// <returns></returns>
        private SelectList TournamentTypeDDL()
        {
            List<SelectListItem> result = new List<SelectListItem>();
            var listAC = (from lst in _TournamenType.All()
                          select new
                          {
                              ID = lst.TournamentTypeID,
                              Name = lst.TournamentTypeName
                          }
                         ).ToList();
            result.AddRange(new SelectList(listAC, "ID", "Name"));
            return new SelectList(result, "Value", "Text");
        }
        private SelectList RanksDDL()
        { 
            List<SelectListItem> result = new List<SelectListItem>();
            var rank = (from lst in Enum.GetValues(typeof(RanksEight)).Cast<RanksEight>()
                        select new
                        {
                            ID = (int)lst,
                            Name = lst.ToString()
                        }).ToList();
            result.AddRange(new SelectList(rank, "ID", "Name"));
            return new SelectList( result,"Value","Text");
        }
        #endregion
    }
}

TableTennisChampionship/TableTennisChampionshipMain/Areas/Administration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - НСИ - Турнири по тенис на маса</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("НСИ - Турнири по тенис на маса", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Играчи", "Index", "PlayerInformation", new { area = "Administration" }, new { })</li>
                    <li>@Html.ActionLink("Турнири", "Index", "Tournament", new { area = "Administration" }, new { })</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - НСИ - Турнири по тенис на маса</p>
        </footer>
    </div>
    <link href="~/Content/CustomCSS.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.structure.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/Custom.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

TableTennisChampionship/TableTennisChampionshipMain/Areas/Administration/Views/Shared/_PlayerCreate.cshtml
@model TableTennisChampionshipMain.ViewModels.TournamentPlayerInfo


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TournamentPlayerInfo</h4>
        <hr />
        @Html.ValidationSummary(true)
        @*<div class="form-group">
            @Html.LabelFor(model => model.TournamentPlayerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TournamentPlayerID)
                @Html.ValidationMessageFor(model => model.TournamentPlayerID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TournamentID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TournamentID)
                @Html.ValidationMessageFor(model => model.TournamentID)
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.PlayerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayerID)
                @Html.ValidationMessageFor(model => model.PlayerID)
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.PlayerFullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayerFullName)
                @Html.ValidationMessageFor(model => model.PlayerFullName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rank, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Rank,(SelectList)ViewBag.Ranks)
                @Html.ValidationMessageFor(model => model.Rank)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PointsForGames, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PointsForGames)
                @Html.ValidationMessageFor(model => model.PointsForGames)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PointsForTournaments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PointsForTournaments)
                @Html.ValidationMessageFor(model => model.PointsForTournaments)
            </div>
        </div><div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}